[theme]

# Used to style primary interface elements. It's the color displayed most frequently across your app's
# screens and components. Examples of widgets using this color are st.slider and st.checkbox.
primaryColor = "#1A5632" # green

# Background color for the main container.
backgroundColor = "#FFFF" # white

# Used as the background for most widgets. Examples of widgets with this background are st.sidebar,
# st.text_input, st.date_input.
secondaryBackgroundColor =  "#ebd2b9" # wheat  "#B4A269" # gold <-- not enough contrast

# Font color for the page.
textColor = "#000000" # black

# Font family (serif | sans serif | mono) for the page. Will not impact code areas.
# Default: "sans serif"
font = "Arial"